# secrets.toml  ← describes what the file is for
OPENAI_API_KEY = "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"
NEWSAPI_KEY    = "a0e78b7a2b224467b188a71b9a6e5b20"
